######################################################################
# Change History
######################################################################
# Date-02/08/2013
# Coder- Michael Lungo 
# Description: Store in s3 bucket, access_key_id and secret_access_key must be in ""
######################################################################

development:
  bucket: teamzoom 
  access_key_id: "AKIAIOYCWZFROQJEEBYQ"
  secret_access_key: "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"
  max_file_size: 104857600
  acl: public-read
    
test:
  bucket: 
  access_key_id: 
  secret_access_key: 
  max_file_size: 104857600
  acl: public-read
  
production:
  bucket: teamzoom 
  access_key_id: "AKIAIOYCWZFROQJEEBYQ"
  secret_access_key: "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"
  max_file_size: 104857600
  acl: public-read
