
development:
  bucket: teamzoom 
  access_key_id: "[ID]"
  secret_access_key: "[KEY]"
  max_file_size: 104857600
  acl: public-read
    
test:
  bucket: 
  access_key_id: 
  secret_access_key: 
  max_file_size: 104857600
  acl: public-read
  
production:
  bucket: teamzoom 
  access_key_id: "[ID]"
  secret_access_key: "[KEY]"
  max_file_size: 104857600
  acl: public-read
