login: &login
  adapter: postgresql
  host: 'ec2-23-23-156-118.compute-1.amazonaws.com'
  username: teamzoom_pro
  password: teamzoom_pro_member
  # host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  host: localhost
  database: teamzoom_dev
  port: 5432
  pool: 5
  timeout: 5000
  
production:
  <<: *login
  database: teamzoom_pro
test:
  <<: *login
  database: teamzoom_test
