#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: teamzoom
  stack: bamboo-ree-1.8.7
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  stack: cedar
  app: teamzoom-stg
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard

testing:
  stack: cedar
  app: teamzoom-test
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard

demo: 
  app: teamzoom-stg
  config: *default
