require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeamsportsController do

  # This should return the minimal set of attributes required to create a valid
  # Teamsport. As you add validations to Teamsport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeamsportsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all teamsports as @teamsports" do
      teamsport = Teamsport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:teamsports).should eq([teamsport])
    end
  end

  describe "GET show" do
    it "assigns the requested teamsport as @teamsport" do
      teamsport = Teamsport.create! valid_attributes
      get :show, {:id => teamsport.to_param}, valid_session
      assigns(:teamsport).should eq(teamsport)
    end
  end

  describe "GET new" do
    it "assigns a new teamsport as @teamsport" do
      get :new, {}, valid_session
      assigns(:teamsport).should be_a_new(Teamsport)
    end
  end

  describe "GET edit" do
    it "assigns the requested teamsport as @teamsport" do
      teamsport = Teamsport.create! valid_attributes
      get :edit, {:id => teamsport.to_param}, valid_session
      assigns(:teamsport).should eq(teamsport)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Teamsport" do
        expect {
          post :create, {:teamsport => valid_attributes}, valid_session
        }.to change(Teamsport, :count).by(1)
      end

      it "assigns a newly created teamsport as @teamsport" do
        post :create, {:teamsport => valid_attributes}, valid_session
        assigns(:teamsport).should be_a(Teamsport)
        assigns(:teamsport).should be_persisted
      end

      it "redirects to the created teamsport" do
        post :create, {:teamsport => valid_attributes}, valid_session
        response.should redirect_to(Teamsport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teamsport as @teamsport" do
        # Trigger the behavior that occurs when invalid params are submitted
        Teamsport.any_instance.stub(:save).and_return(false)
        post :create, {:teamsport => {}}, valid_session
        assigns(:teamsport).should be_a_new(Teamsport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Teamsport.any_instance.stub(:save).and_return(false)
        post :create, {:teamsport => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teamsport" do
        teamsport = Teamsport.create! valid_attributes
        # Assuming there are no other teamsports in the database, this
        # specifies that the Teamsport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Teamsport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => teamsport.to_param, :teamsport => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested teamsport as @teamsport" do
        teamsport = Teamsport.create! valid_attributes
        put :update, {:id => teamsport.to_param, :teamsport => valid_attributes}, valid_session
        assigns(:teamsport).should eq(teamsport)
      end

      it "redirects to the teamsport" do
        teamsport = Teamsport.create! valid_attributes
        put :update, {:id => teamsport.to_param, :teamsport => valid_attributes}, valid_session
        response.should redirect_to(teamsport)
      end
    end

    describe "with invalid params" do
      it "assigns the teamsport as @teamsport" do
        teamsport = Teamsport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Teamsport.any_instance.stub(:save).and_return(false)
        put :update, {:id => teamsport.to_param, :teamsport => {}}, valid_session
        assigns(:teamsport).should eq(teamsport)
      end

      it "re-renders the 'edit' template" do
        teamsport = Teamsport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Teamsport.any_instance.stub(:save).and_return(false)
        put :update, {:id => teamsport.to_param, :teamsport => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teamsport" do
      teamsport = Teamsport.create! valid_attributes
      expect {
        delete :destroy, {:id => teamsport.to_param}, valid_session
      }.to change(Teamsport, :count).by(-1)
    end

    it "redirects to the teamsports list" do
      teamsport = Teamsport.create! valid_attributes
      delete :destroy, {:id => teamsport.to_param}, valid_session
      response.should redirect_to(teamsports_url)
    end
  end

end
